### ISSUE TITLE
accounts_payout can be optimized with generator pattern

### ISSUE THREAD

**Issue by SeiryuZ** [Lumenaut-Network/pool#2]
The `accounts_payout` method (https://github.com/Lumenaut-Network/pool/blob/master/generate.py#L53-L76) can use generator pattern (https://wiki.python.org/moin/Generators) to keep the memory low

This is especially important if we want to use lower end machines to host the script

**Edit
My proposal, instead of holding everything in one huge list, use generator pattern to process the list as it is generated to save memory.

```python
def accounts_payout(connection, pool_addr, inflation, size=100):
        # snipped
	while True:
		# get current batch
		yield payout_batch

	donation_payouts = []
	batch = []
	for address, amount in donations.items():
		batch.append((address, amount))
		if len(batch) >= size:
			yield donation_batch
			batch = []
```

**Comment by matheusb-comp** [comment]
We can't separate the calculation of the payout in batches, since one voter could donate part of their inflation to another voter.
If the payout to A is calculated, and then in a different batch B donates 50% of their inflation to A, the payout would have to be recalculated.

My ideia is to consider the users donating "votes" to one another, calculate and change the number of votes for all voters, and then calculate the payouts.
